strict mode and best practices

diff --git a/cics b/cics
--- a/cics
+++ b/cics
@@ -1,164 +1,180 @@
 #!/usr/bin/env sh
-set -e
-SCRIPT_PATH="$(
-    cd -- "$(dirname "$0")" >/dev/null 2>&1 || exit
+## Strict mode
+set -eu
+IFS="(printf '\n\t')"
+readonly IFS
+## Prologue
+if ! [ "$(command -v docker)" ]; then
+    echo 'ERROR: Missing required command '\''docker'\'''
+    exit 1
+fi
+cics_script_path="$(
+    script_directory="$(dirname "${0}")"
+    cd -- "${script_directory}" >/dev/null 2>&1
     pwd -P
 )"
+cics_shebang='#!/usr/bin/env -S cics run'
+readonly cics_shebang cics_script_path PWD
 ## Help
-print_help() {
-    printf "Cics Installs Container Shims\n\nUsage:\n    %-16s\n\nCommands:\n    %-16s\n    %-16s\n    %-16s\n    %-16s\n\nRun 'cics COMMAND --help' for more information on a command\n\nExamples:\n    %-16s\n    %-16s\n    %-16s\n    %-16s\n    %-16s\n\nLimitations:\n    %-16s\n    %-16s\n" \
+cics_print_help() {
+    printf 'Cics Installs Container Shims\n\nUsage:\n    %-40s\n\nCommands:\n    %-40s\n    %-40s\n    %-40s\n    %-40s\n\nExamples:\n    %-40s%-40s\n    %-40s%-40s\n\nRun '\''cics COMMAND --help'\'' for more information on a command\n' \
         'cics [-h, --help] COMMAND' \
         'install' 'list' 'run' 'uninstall' \
-        'cics install ghcr.io/hadolint/hadolint' 'cics list' 'cics run hadolint -v' 'hadolint -v' 'cics uninstall hadolint' \
-        'No access to directories above current working directory' 'No port forwarding'
+        'cics install ghcr.io/hadolint/hadolint' '# Install hadolint shim' 'hadolint -v' '# Run shim without access to parent directories or ports'
 }
-print_install_help() {
-    printf 'Install one or more container shims\n\nUsage:\n     %-16s\n' \
-        'cics install IMAGE...'
+cics_print_install_help() {
+    printf 'Install one or more container shims\n\nUsage:\n     %-40s\n' 'cics install image...'
 }
-
-print_list_help() {
-    printf 'List installed shims\n\nUsage:\n     %-16s\n' \
-        'cics list'
+cics_print_list_help() {
+    printf 'List installed shims\n\nUsage:\n     %-40s\n' 'cics list'
 }
-print_run_help() {
-    printf 'Manually run a shim. Used by cics to interpret shims.\n\nUsage:\n     %-16s\n' \
-        'cics run SHIM'
+cics_print_run_help() {
+    printf 'Manually run a shim. Used by cics to interpret shims.\n\nUsage:\n     %-40s\n' 'cics run SHIM'
 }
-print_uninstall_help() {
-    printf 'Uninstall one or more shims\n\nUsage:\n     %-16s\n' \
-        'cics uninstall SHIM...'
+cics_print_uninstall_help() {
+    printf 'Uninstall one or more shims\n\nUsage:\n     %-40s\n' 'cics uninstall SHIM...'
 }
 ## CLI
 if [ 0 -eq "${#}" ]; then
-    print_help
+    cics_print_help
     exit 1
 fi
-case "${1}" in
+cics_command="${1}"
+readonly cics_command
+case "${cics_command}" in
     -h | --help)
-        print_help
+        cics_print_help
         exit 0
         ;;
     *) ;;
 esac
-COMMAND="${1}"
-case "${2}" in
-    -h | --help)
-        case "${COMMAND}" in
-            install)
-                print_install_help
-                ;;
-            list)
-                print_list_help
-                ;;
-            run)
-                print_run_help
-                ;;
-            uninstall)
-                print_uninstall_help
-                ;;
-            *)
-                print_help
-                exit 1
-                ;;
-        esac
-        exit 0
-        ;;
-    *) ;;
-esac
+if [ 1 -lt "${#}" ]; then
+    case "${2}" in
+        -h | --help)
+            case "${cics_command}" in
+                install)
+                    cics_print_install_help
+                    ;;
+                list)
+                    cics_print_list_help
+                    ;;
+                run)
+                    cics_print_run_help
+                    ;;
+                uninstall)
+                    cics_print_uninstall_help
+                    ;;
+                *)
+                    cics_print_help
+                    exit 1
+                    ;;
+            esac
+            exit 0
+            ;;
+        *) ;;
+    esac
+fi
 shift
 ## Process
-CICS_SHEBANG='#!/usr/bin/env -S cics run'
 # cics_list
 cics_list() {
-    for CICS_LIST_FILE in "${SCRIPT_PATH}/"*; do
-        if [ -f "${CICS_LIST_FILE}" ] && head -1 "${CICS_LIST_FILE}" | grep -q "^${CICS_SHEBANG}\$"; then
-            basename "${CICS_LIST_FILE}"
-        fi
-    done
+    (
+        for filename in "${cics_script_path}/"*; do
+            if [ -f "${filename}" ] && head -1 "${filename}" | grep -q "^${cics_shebang}\$"; then
+                basename "${filename}"
+            fi
+        done
+    )
 }
-# TODO multiple IMAGE and SHIM
 # cics_install IMAGE...
 cics_install() {
-    CICS_INSTALL_EXISTS_LIST="$(cics_list)"
+    (
+        installed_shims="$(cics_list)"
+        readonly installed_shims
 
-    for CICS_INSTALL_ARG in "${@}"; do
-        CICS_INSTALL_ENTRYPOINT="${CICS_INSTALL_ARG##*/}"
-        CICS_INSTALL_ENTRYPOINT="${CICS_INSTALL_ENTRYPOINT%%:*}"
+        for arg in "${@}"; do
+            entrypoint="${arg##*/}"
+            entrypoint="${entrypoint%%:*}"
 
-        if echo "${CICS_INSTALL_EXISTS_LIST}" | grep -q "^${CICS_INSTALL_ENTRYPOINT}\$"; then
-            echo "ERROR: '${CICS_INSTALL_ENTRYPOINT}' is already a container shim. Reinstall to change container repository and/or tag."
-            return 1
-        fi
+            if echo "${installed_shims}" | grep -q "^${entrypoint}\$"; then
+                echo "ERROR: '${entrypoint}' is already installed. Reinstall to change container repository and/or tag."
+                exit 1
+            fi
 
-        CICS_INSTALL_TARGET="${SCRIPT_PATH}/${CICS_INSTALL_ENTRYPOINT}"
-
-        printf '%s\n%s\n' "${CICS_SHEBANG}" "${CICS_INSTALL_ARG}" >"${CICS_INSTALL_TARGET}"
-        chmod +x "${CICS_INSTALL_TARGET}"
-    done
+            install_target="${cics_script_path}/${entrypoint}"
+            printf '%s\n%s\n' "${cics_shebang}" "${arg}" >"${install_target}"
+            chmod +x "${install_target}"
+        done
+    )
 }
 # cics_run SHIM
 cics_run() {
-    CICS_RUN_IMAGE="$(tail -n 1 "${1}")"
-    CICS_RUN_ENTRYPOINT="${CICS_RUN_IMAGE##*/}"
-    CICS_RUN_ENTRYPOINT="${CICS_RUN_ENTRYPOINT%%:*}"
-    if [ -z "${CICS_RUN_IMAGE}" ] || [ -z "${CICS_RUN_ENTRYPOINT}" ]; then
-        return 1
-    fi
+    (
+        image="$(tail -n 1 "${cics_script_path}/${1}")"
+        entrypoint="${image##*/}"
+        entrypoint="${entrypoint%%:*}"
+        if [ -z "${entrypoint}" ]; then
+            exit 1
+        fi
+        readonly entrypoint image
 
-    for CICS_RUN_ARG in "${@}"; do
-        set -- "${@}" "$(echo "${CICS_RUN_ARG}" | sed -e "s|${PWD}|/mnt|g" || true)"
-        shift
-    done
+        for arg in "${@}"; do
+            set -- "${@}" "$(echo "${arg}" | sed -e "s|${PWD}|/mnt|")"
+            shift
+        done
 
-    docker run -iq --rm --pull always -v "${PWD}:/mnt" -w /mnt "${CICS_RUN_IMAGE}" "${CICS_RUN_ENTRYPOINT}" "${@}"
+        docker run -iq --rm --pull always -v "${PWD}:/mnt" -w /mnt "${image}" "${entrypoint}" "${@}"
+    )
 }
 # cics_uninstall SHIM...
 cics_uninstall() {
-    CICS_UNINSTALL_EXISTS_LIST="$(cics_list)"
+    (
+        installed_shims="$(cics_list)"
+        readonly installed_shims
 
-    for CICS_UNINSTALL_ARG in "${@}"; do
-        if ! echo "${CICS_UNINSTALL_EXISTS_LIST}" | grep -q "^${CICS_UNINSTALL_ARG}\$"; then
-            echo "ERROR: ${CICS_UNINSTALL_ARG} is not a container shim"
-            return 1
-        fi
-        set -- "${@}" "${SCRIPT_PATH}/${CICS_UNINSTALL_ARG}"
-        shift
-    done
+        for arg in "${@}"; do
+            if ! echo "${installed_shims}" | grep -q "^${arg}\$"; then
+                echo "ERROR: ${arg} is not installed"
+                exit 1
+            fi
+            set -- "${@}" "${cics_script_path}/${arg}"
+            shift
+        done
 
-    rm -f -- "${@}"
+        rm -f -- "${@}"
+    )
 }
-case "${COMMAND}" in
+case "${cics_command}" in
     install)
-        if [ '0' -eq "${#}" ]; then
-            print_install_help
+        if [ 0 -eq "${#}" ]; then
+            cics_print_install_help
             exit 1
         fi
         cics_install "${@}"
         ;;
     list)
-        if [ '0' -ne "${#}" ]; then
-            print_list_help
+        if [ 0 -ne "${#}" ]; then
+            cics_print_list_help
             exit 1
         fi
         cics_list
         ;;
     run)
-        if [ '1' -ne "${#}" ]; then
-            print_run_help
+        if [ 0 -eq "${#}" ]; then
+            cics_print_run_help
             exit 1
         fi
-        cics_run "${1}"
+        cics_run "${@}"
         ;;
     uninstall)
-        if [ '0' -eq "${#}" ]; then
-            print_uninstall_help
+        if [ 0 -eq "${#}" ]; then
+            cics_print_uninstall_help
             exit 1
         fi
         cics_uninstall "${@}"
         ;;
     *)
-        print_help
+        cics_print_help
         exit 1
         ;;
 esac
